#!/bin/bash

aws s3 cp accMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp blcaMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp brcaMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp cescMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp cholMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp coadMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp dlbcMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp escaMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp gbmMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp hnscMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp kichMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp kircMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp kirpMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp lamlMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp lggMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp lihcMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp luadMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp luscMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp mesoMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp ovMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp paadMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp pcpgMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp pradMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp readMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp sarcMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp skcmMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp stadMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp tgctMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp thcaMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp thymMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp ucecMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp ucsMAEO.rds s3://multiassayexperiments/ --acl public-read
aws s3 cp uvmMAEO.rds s3://multiassayexperiments/ --acl public-read
