---
title: "Building MultiAssayExperiment from Firehose"
author: "Marcel Ramos"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r,include=TRUE,results="hide",message=FALSE,warning=FALSE}
library(MultiAssayExperiment.TCGA)
library(BiocParallel)
params <- MulticoreParam(
    workers = 33, stop.on.error = FALSE, progressbar = TRUE
)
```

# Create all directories needed in repository

```{r}
dataDirectories(create = TRUE)
```

## Download all available resources

```{r}
TCGAcodes <- getDiseaseCodes()
getClinicalData(TCGAcodes = TCGAcodes, nworkers = 34)
downloadExtraClinical(TCGAcodes = TCGAcodes)
```

## Download SubType data from DropBox

Note. Authentication required using `rdrop2`

ALTERNATIVELY: You can download files manually and put them in
`inst/extdata/allsubtypes`

```{r}
## Authenticate to Dropbox API at FIRST RUN
# drop_auth()
# drop_acc() %>% select(uid, display_name, email_verified, quota_info.quota)

downloadSubtypeDrop(TCGAcodes = TCGAcodes)
```

## Merge curated data to clinical data

```{r}
mergeSubtypeCuration(TCGAcodes = TCGAcodes)
```

## Clean merged data files

```{r}
cleanMerged(TCGAcodes = TCGAcodes, runDate = "20160128", nworkers = 34)
```

## Build and upload MultiAssayExperiment data

```{r}
setwd("~/gh/MultiAssayExperiment.TCGA")
res <- bptry({
    bplapply(X = TCGAcodes, FUN = function(code) {
        buildMultiAssayExperiment(
            code,
            dataType = "miRNASeqGene",
            version = "2.1.0",
            upload = TRUE,
            update = TRUE
        )
    }, BPPARAM = params)
})
```

```{r,eval=FALSE}
setwd("~/gh/MultiAssayExperiment.TCGA")
devtools::load_all()
library(BiocParallel)
registered()
params <- MulticoreParam(
    workers = 5, stop.on.error = FALSE, progressbar = TRUE
)
## currently failing
restCodes <- c("KIRC", "CHOL", "PAAD", "THCA", "UCS")
retest <- bptry({
    bplapply(X = restCodes, FUN = function(code) {
        devtools::load_all("~/gh/MultiAssayExperiment.TCGA")
        buildMultiAssayExperiment(
            code, upload = TRUE, version = "2.0.1", update = TRUE
        )
    }, BPPARAM = params)
})
```
