install.packages("devtools", repos = "http://cran.r-project.org")
source("https://bioconductor.org/biocLite.R")
useDevel()
biocLite()
BiocInstaller::biocLite("vjcitn/MultiAssayExperiment")
BiocInstaller::biocLite("LiNk-NY/RTCGAToolbox")
BiocInstaller::biocLite("waldronlab/BiocInterfaces")
BiocInstaller::biocLite("karthik/rdrop2")
install.packages("readr", repos = "http://cran.r-project.org")
